Repository googleinterns/step1-2020, pull requests merged in 2020-07, with the labels that each got.

#24 Update readme project name
  README.md
Labels: cla: yes

#15 Redirect to search.jsp
  src/main/webapp/WEB-INF/templates/search.jsp
Labels: cla: yes

#25 update card class to remove setter
  src/main/java/com/google/step/snippet/data/Card.java
Labels: cla: yes

#34 Add geeks scraper
  src/main/java/com/google/step/snippet/external/GeeksForGeeksClient.java
Labels: cla: yes

#32 remove unused attribute
  src/main/java/com/google/step/snippet/servlets/HomepageServlet.java
Labels: cla: yes, front end

#35 Add license, contributing, and readme setup
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: cla: yes, documentation

#18 Revert http code to be compatible with Java 8 deploy
  .github/workflows/build.yaml
  README.md
  pom.xml
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
Labels: cla: yes, servlet

#29 Add w3client unit tests
  README.md
  pom.xml
  src/main/java/com/google/step/snippet/data/Card.java
  src/main/java/com/google/step/snippet/external/W3SchoolsClient.java
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
  src/test/java/com/google/step/snippet/W3SchoolsClientTest.java
Labels: cla: yes, tests

#40 Change homepage cse id
  src/main/webapp/WEB-INF/tags/head.tag
Labels: cla: yes, front end

#43 Add card display to srp (updated)
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
  src/main/webapp/WEB-INF/tags/head.tag
  src/main/webapp/WEB-INF/templates/search.jsp
  src/main/webapp/css/srp_style.css
  src/main/webapp/css/style.css
  src/main/webapp/style.css
Labels: cla: yes, front end

#33 add Client interface
  .gitignore
  pom.xml
  src/main/java/com/google/step/snippet/data/Card.java
  src/main/java/com/google/step/snippet/external/Client.java
  src/main/java/com/google/step/snippet/external/GeeksForGeeksClient.java
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/main/java/com/google/step/snippet/external/W3SchoolsClient.java
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
  src/test/java/com/google/step/snippet/W3SchoolsClientTest.java
Labels: cla: yes, servlet

#41 Add logo style
  src/main/webapp/WEB-INF/tags/base.tag
  src/main/webapp/css/style.css
Labels: cla: yes, front end

#50 Move tests to external folder
  src/test/java/com/google/step/snippet/external/W3SchoolsClientTest.java
Labels: cla: yes, tests

#56 Fix package path
  src/test/java/com/google/step/snippet/external/W3SchoolsClientTest.java
Labels: bug, cla: yes, pod approved

#36 Add Login/Logout button to homepage and search page
  pom.xml
  src/main/java/com/google/step/snippet/servlets/HomepageServlet.java
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
  src/main/webapp/WEB-INF/tags/base.tag
  src/main/webapp/WEB-INF/templates/homepage.jsp
  src/main/webapp/WEB-INF/templates/search.jsp
  src/main/webapp/css/srp_style.css
  src/main/webapp/css/style.css
Labels: cla: yes, front end, pod approved, servlet

#54 Fix 500 error when stackoverflow post is unanswered
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/main/java/com/google/step/snippet/external/W3SchoolsClient.java
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
Labels: bug, cla: yes, high priority, pod approved

#73 Fixed Null link check
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
Labels: bug, cla: yes, high priority, pod approved

#59 Add styling to Homepage and SRP searchbox view
  src/main/webapp/WEB-INF/tags/base.tag
  src/main/webapp/WEB-INF/templates/homepage.jsp
  src/main/webapp/css/home_style.css
  src/main/webapp/css/srp_style.css
  src/main/webapp/css/style.css
Labels: cla: yes, front end, pod approved

#77 Remove unused searchbox styling
  src/main/webapp/css/srp_style.css
Labels: cla: yes

#52 Add site source icon
  src/main/java/com/google/step/snippet/data/Card.java
  src/main/java/com/google/step/snippet/external/GeeksForGeeksClient.java
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/main/java/com/google/step/snippet/external/W3SchoolsClient.java
  src/main/webapp/WEB-INF/templates/search.jsp
  src/main/webapp/css/srp_style.css
  src/test/java/com/google/step/snippet/external/W3SchoolsClientTest.java
Labels: cla: yes, front end, pod approved

#42 Parallelize search servlet
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
Labels: cla: yes, pod approved, servlet

#63 remove code and only display the description in SO client
  src/main/java/com/google/step/snippet/data/Card.java
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/main/webapp/WEB-INF/templates/search.jsp
Labels: cla: yes, front end, high priority, pod approved

#70 Stackoverflow tests
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/test/java/com/google/step/snippet/external/StackOverflowClientTest.java
Labels: cla: yes, pod approved, tests

#69 Remove title attribute
  src/main/webapp/WEB-INF/templates/search.jsp
Labels: cla: yes, front end, pod approved

#74 Sanitize and escape html
  pom.xml
  src/main/java/com/google/step/snippet/external/Client.java
  src/main/java/com/google/step/snippet/external/GeeksForGeeksClient.java
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/main/java/com/google/step/snippet/external/W3SchoolsClient.java
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
  src/test/java/com/google/step/snippet/external/StackOverflowClientTest.java
  src/test/java/com/google/step/snippet/external/W3SchoolsClientTest.java
Labels: cla: yes, front end, high priority, pod approved

#89 Revert "Merge pull request #74 from googleinterns/html-escape"
  pom.xml
  src/main/java/com/google/step/snippet/external/Client.java
  src/main/java/com/google/step/snippet/external/GeeksForGeeksClient.java
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/main/java/com/google/step/snippet/external/W3SchoolsClient.java
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
  src/test/java/com/google/step/snippet/external/StackOverflowClientTest.java
  src/test/java/com/google/step/snippet/external/W3SchoolsClientTest.java
Labels: cla: yes

#93 Revert "Revert "Merge pull request #74 from googleinterns/html-escape""
  pom.xml
  src/main/java/com/google/step/snippet/external/Client.java
  src/main/java/com/google/step/snippet/external/GeeksForGeeksClient.java
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/main/java/com/google/step/snippet/external/W3SchoolsClient.java
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
  src/test/java/com/google/step/snippet/external/StackOverflowClientTest.java
  src/test/java/com/google/step/snippet/external/W3SchoolsClientTest.java
Labels: cla: yes, high priority

#83 Improve description retrieval for W3Schools
  src/main/java/com/google/step/snippet/external/W3SchoolsClient.java
Labels: cla: yes, enhance, pod approved

#96 GeeksForGeeks Tests
  src/test/java/com/google/step/snippet/external/GeeksForGeeksClientTest.java
Labels: cla: yes, high priority, pod approved

#87 Add HTML escaping tests
  src/test/java/com/google/step/snippet/external/W3SchoolsClientTest.java
Labels: cla: yes, pod approved, tests

#101 Add searchbox with suggestions
  src/main/webapp/WEB-INF/tags/head.tag
Labels: cla: yes, high priority, pod approved

#100 Sanitizing SO client
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/test/java/com/google/step/snippet/external/StackOverflowClientTest.java
Labels: cla: yes, high priority, pod approved, tests

#76 Add Feedback Voting UI
  src/main/java/com/google/step/snippet/data/Card.java
  src/main/java/com/google/step/snippet/external/Client.java
  src/main/java/com/google/step/snippet/external/GeeksForGeeksClient.java
  src/main/java/com/google/step/snippet/external/StackOverflowClient.java
  src/main/java/com/google/step/snippet/external/W3SchoolsClient.java
  src/main/webapp/WEB-INF/appengine-web.xml
  src/main/webapp/WEB-INF/templates/search.jsp
  src/main/webapp/css/srp_style.css
  src/main/webapp/js/example.js
  src/main/webapp/js/script.js
  src/test/java/com/google/step/snippet/external/GeeksForGeeksClientTest.java
  src/test/java/com/google/step/snippet/external/StackOverflowClientTest.java
  src/test/java/com/google/step/snippet/external/W3SchoolsClientTest.java
Labels: cla: yes, front end, pod approved

#82 Account page setting UI
  src/main/java/com/google/step/snippet/servlets/UserSettingServlet.java
  src/main/webapp/WEB-INF/templates/user_dashboard.jsp
  src/main/webapp/css/style.css
  src/main/webapp/css/user_style.css
Labels: cla: yes, front end, high priority, pod approved

#84 Setting servlet
  src/main/java/com/google/step/snippet/data/User.java
  src/main/java/com/google/step/snippet/servlets/UserSettingServlet.java
  src/main/webapp/WEB-INF/tags/base.tag
  src/main/webapp/WEB-INF/templates/user_dashboard.jsp
  src/main/webapp/css/home_style.css
  src/main/webapp/css/srp_style.css
  src/main/webapp/css/style.css
  src/main/webapp/css/user_style.css
Labels: cla: yes, high priority, pod approved, servlet

#92 Implement sorted display
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
Labels: cla: yes, pod approved, servlet
