Repository googleinterns/step1-2020, pull requests merged in 2020-08, with the labels that each got.

#95 Add primary language feature
  src/main/java/com/google/step/snippet/data/Languages.java
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
Labels: cla: yes, pod approved

#99 Implement Voting Feedback with Authentication
  src/main/java/com/google/step/snippet/external/Client.java
  src/main/java/com/google/step/snippet/servlets/FeedbackServlet.java
  src/main/java/com/google/step/snippet/servlets/SearchServlet.java
  src/main/webapp/css/srp_style.css
  src/test/java/com/google/step/snippet/external/GeeksForGeeksClientTest.java
  src/test/java/com/google/step/snippet/external/StackOverflowClientTest.java
  src/test/java/com/google/step/snippet/external/W3SchoolsClientTest.java
Labels: cla: yes, pod approved, servlet

#102 Update README
  README.md
Labels: cla: yes
